# Generated by Django 6.1 on 2026-08-19 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Habit",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("place", models.CharField(max_length=255, verbose_name="Место")),
                ("time", models.TimeField(verbose_name="Время выполнения")),
                ("action", models.CharField(max_length=255, verbose_name="Действие")),
                ("is_pleasant", models.BooleanField(default=False, verbose_name="Признак приятной привычки")),
                (
                    "periodicity",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Через сколько дней повторять. Минимум 1.",
                        verbose_name="Периодичность (в днях)",
                    ),
                ),
                ("reward", models.CharField(blank=True, max_length=255, verbose_name="Вознаграждение")),
                (
                    "execution_time",
                    models.PositiveSmallIntegerField(default=120, verbose_name="Время на выполнение (сек)"),
                ),
                ("is_public", models.BooleanField(default=False, verbose_name="Публичная привычка")),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
                (
                    "related_habit",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"is_pleasant": True},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="related_to",
                        to="api.habit",
                        verbose_name="Связанная привычка",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
                "ordering": ["-time"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("related_habit__isnull", False),
                            models.Q(
                                ("reward__isnull", False), models.Q(("reward", ""), _negated=True), _connector="OR"
                            ),
                            _negated=True,
                        ),
                        name="no_reward_and_related_habit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("execution_time__lte", 120)), name="execution_time_lte_120"
                    ),
                    models.CheckConstraint(condition=models.Q(("periodicity__lte", 7)), name="periodicity_lte_7"),
                ],
            },
        ),
    ]
