# Generated by Django 6.1 on 2026-08-21 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="telegram_chat_id",
            field=models.BigIntegerField(blank=True, null=True, verbose_name="ID чата Telegram"),
        ),
    ]
